import {API} from '../api/api.js';import {router} from '../core/router.js';import {appState} from '../core/state.js';import {toast} from '../ui/toast.js';import {createTimer} from '../game/timer.js';import {gameEngine} from '../game/gameEngine.js';
let timer=null,poll=null,answered=false;
export function gamePage(){return `<div class="shell page"><header class="topbar"><div class="brand">GEO<span>BATTLE</span></div><div class="timer" id="timer">--</div></header><div class="game-head"><div><div class="eyebrow" id="counter">CARREGANDO...</div><div class="progress"><div id="progress" style="width:0"></div></div></div><div class="host-badge">${appState.get().session.isHost?'👑 Host':''}</div></div><main id="game-area" class="card pad">Carregando pergunta...</main></div>`}
function renderQuestion(data){const q=data.question;document.querySelector('#counter').textContent=gameEngine.formatQuestionNumber(data.index,data.total);document.querySelector('#progress').style.width=`${((data.index)/data.total)*100}%`;document.querySelector('#game-area').innerHTML=`<div class="question-meta"><span class="chip active">${q.category}</span><span class="chip">${q.difficulty}</span></div><h1 class="question">${q.question}</h1><div class="answers">${q.alternatives.map((a,i)=>`<button class="answer" data-answer="${i}"><strong>${String.fromCharCode(65+i)}.</strong> ${a}</button>`).join('')}</div><div id="result-panel"></div>`;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>submit(Number(b.dataset.answer),data))}
async function submit(answer,data){if(answered)return;answered=true;document.querySelectorAll('.answer').forEach(b=>b.disabled=true);const start=data.startedAt;try{const result=await API.submitAnswer({roomCode:appState.get().session.roomCode,playerId:appState.get().session.playerId,questionId:data.question.id,answer});toast('Resposta registrada!','success');showResult(await API.getQuestionResult({roomCode:appState.get().session.roomCode,playerId:appState.get().session.playerId}),result.record)}catch(e){toast(e.message,'error');if(e.code==='TIME_EXPIRED')showResult(await API.getQuestionResult({roomCode:appState.get().session.roomCode,playerId:appState.get().session.playerId}),null)} }
function showResult(result,own){const panel=document.querySelector('#result-panel');const s=appState.get();const mode=s.settings?.mode||s.room?.settings?.mode;const training=mode==='training';panel.innerHTML=`<div class="result-panel explanation"><strong>${own?.correct?'Resposta registrada — você acertou!':own?'Resposta registrada — não foi dessa vez.':'Tempo esgotado.'}</strong><p>Resposta correta: <b>${String.fromCharCode(65+result.correctAnswer)}</b>. ${result.explanation}</p><p>${result.correctCount} de ${result.answeredCount} respostas registradas acertaram.</p><h3>Ranking parcial</h3><div class="list">${result.ranking.slice(0,5).map(x=>`<div class="list-item"><span>${x.position}º — ${x.name}</span><b>${x.score}</b></div>`).join('')}</div>${s.session.isHost?`<button class="btn" id="next" style="margin-top:18px">${result.ranking.length?'PRÓXIMA':'CONTINUAR'}</button>`:'<div class="waiting">Aguardando o anfitrião...</div>'}${training?'<p class="muted">Modo treino: neste modo o feedback é imediato.</p>':''}</div>`;document.querySelector('#next')?.addEventListener('click',next)}
async function next(){const s=appState.get();try{const r=await API.nextQuestion({roomCode:s.session.roomCode,hostId:s.session.playerId});appState.set({room:r});if(r.status==='FINISHED')router.navigate('results');else{answered=false;load()}}catch(e){toast(e.message,'error')}}
async function load(){const s=appState.get();try{const data=await API.getQuestion({roomCode:s.session.roomCode,playerId:s.session.playerId});if(!data){router.navigate('lobby');return}answered=false;renderQuestion(data);clearInterval(poll);timer?.stop();timer=createTimer(data.timeLimit,{onTick:n=>document.querySelector('#timer').textContent=n,onEnd:()=>{if(!answered){answered=true;toast('Tempo esgotado.','error');API.getQuestionResult({roomCode:s.session.roomCode,playerId:s.session.playerId}).then(r=>showResult(r,null)).catch(()=>{})}}});poll=setInterval(async()=>{try{const r=await API.getRoom({roomCode:s.session.roomCode,playerId:s.session.playerId});if(r.status==='FINISHED')router.navigate('results')}catch{}},1800)}catch(e){toast(e.message,'error')}}
export function bindGame(){load()}
