import {QUESTIONS} from '../data/questions.js';
import {calculateScore} from '../game/scoring.js';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const alphabet='ABCDEFGHJKMNPQRSTUVWXYZ23456789';
const db={rooms:new Map()};
function id(prefix){return prefix+'_'+crypto.randomUUID().replaceAll('-','').slice(0,12)}
function code(){let s='';for(let i=0;i<6;i++)s+=alphabet[Math.floor(Math.random()*alphabet.length)];return s}
function chooseQuestions(settings){let pool=QUESTIONS.filter(q=>(settings.categories||[]).includes(q.category));if(!pool.length)pool=[...QUESTIONS];if(settings.difficulty!=='random')pool=pool.filter(q=>q.difficulty===settings.difficulty)||pool;pool=[...pool].sort(()=>Math.random()-.5);return pool.slice(0,settings.questionCount)}
function publicRoom(r){return JSON.parse(JSON.stringify({roomId:r.roomId,roomCode:r.roomCode,hostId:r.hostId,status:r.status,players:r.players,settings:r.settings,currentQuestion:r.currentQuestion,questionStartedAt:r.questionStartedAt,questionIndex:r.questionIndex,totalQuestions:r.questions.length}))}
async function createRoom({hostName,settings}){await delay(350);const roomId=id('room'),hostId=id('host'),roomCode=code();const qs=chooseQuestions(settings);const host={playerId:hostId,name:hostName,score:0,answers:[],correctAnswers:0,wrongAnswers:0,streak:0,maxStreak:0,alive:true,joinedAt:Date.now(),isHost:true};const r={roomId,roomCode,hostId,status:'WAITING',players:[host],settings,questions:qs,questionIndex:0,currentQuestion:null,questionStartedAt:null,answersByQuestion:new Map(),result:null,createdAt:Date.now()};db.rooms.set(roomCode,r);return {room:publicRoom(r),session:{roomCode,playerId:hostId,playerName:hostName,isHost:true}}}
async function joinRoom({roomCode,name}){await delay(300);const r=db.rooms.get(roomCode);if(!r)throwError('ROOM_NOT_FOUND','Sala não encontrada.');if(r.status!=='WAITING'&&!r.settings.allowLateJoin)throwError('GAME_ALREADY_STARTED','A partida já começou.');if(r.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))throwError('NAME_ALREADY_EXISTS','Seu nome já está sendo usado.');const p={playerId:id('player'),name,score:0,answers:[],correctAnswers:0,wrongAnswers:0,streak:0,maxStreak:0,alive:true,joinedAt:Date.now(),isHost:false};r.players.push(p);return{room:publicRoom(r),session:{roomCode,playerId:p.playerId,playerName:name,isHost:false}}}
function get(r,playerId){const p=r.players.find(x=>x.playerId===playerId);if(!p)throwError('PLAYER_NOT_FOUND','Jogador não encontrado.');return p}
function throwError(code,message){const e=new Error(message);e.code=code;throw e}
async function getRoom({roomCode,playerId}){await delay(120);const r=db.rooms.get(roomCode);if(!r)throwError('ROOM_NOT_FOUND','Sala não encontrada.');get(r,playerId);return publicRoom(r)}
async function startGame({roomCode,hostId}){await delay(250);const r=db.rooms.get(roomCode);if(!r)throwError('ROOM_NOT_FOUND','Sala não encontrada.');if(r.hostId!==hostId)throwError('UNAUTHORIZED','Somente o anfitrião pode iniciar.');if(r.players.length<1)throwError('INVALID_REQUEST','É necessário ter jogadores.');r.status='QUESTION';r.questionIndex=0;r.currentQuestion=r.questions[0].id;r.questionStartedAt=Date.now();r.answersByQuestion.set(r.currentQuestion,new Map());return publicRoom(r)}
async function getQuestion({roomCode,playerId}){await delay(100);const r=db.rooms.get(roomCode);get(r,playerId);if(r.status!=='QUESTION')return null;const q=r.questions[r.questionIndex];return{index:r.questionIndex,total:r.questions.length,question:{id:q.id,category:q.category,difficulty:q.difficulty,question:q.question,alternatives:q.alternatives},startedAt:r.questionStartedAt,timeLimit:r.settings.questionTime}}
async function submitAnswer({roomCode,playerId,questionId,answer}){await delay(180);const r=db.rooms.get(roomCode);const p=get(r,playerId);if(r.status!=='QUESTION')throwError('INVALID_REQUEST','A pergunta não está ativa.');const q=r.questions[r.questionIndex];if(q.id!==Number(questionId))throwError('INVALID_QUESTION','Pergunta inválida.');const map=r.answersByQuestion.get(q.id)||new Map();if(map.has(playerId))throwError('ALREADY_ANSWERED','Você já respondeu essa pergunta.');const elapsed=Date.now()-r.questionStartedAt;if(elapsed>r.settings.questionTime*1000)throwError('TIME_EXPIRED','Tempo esgotado.');const correct=Number(answer)===q.correctAnswer;const nextStreak=correct?p.streak+1:0;const points=calculateScore({correct,responseMs:elapsed,questionTimeMs:r.settings.questionTime*1000,streak:nextStreak});const rec={answerId:id('answer'),playerId,questionId:q.id,answer:Number(answer),correct,responseTime:elapsed,points,timestamp:Date.now()};map.set(playerId,rec);r.answersByQuestion.set(q.id,map);p.answers.push(rec);p.score+=points;p.streak=nextStreak;p.maxStreak=Math.max(p.maxStreak,p.streak);if(correct)p.correctAnswers++;else{p.wrongAnswers++;if(r.settings.mode==='survival')p.alive=p.alive&&p.wrongAnswers<3}
if(p.isHost){for(const bot of r.players.filter(x=>x.isBot&&x.alive&&!map.has(x.playerId))){const botCorrect=Math.random()>.3;const botElapsed=Math.floor(r.settings.questionTime*1000*(.2+.7*Math.random()));const botAnswer=botCorrect?q.correctAnswer:((q.correctAnswer+1+Math.floor(Math.random()*3))%4);const bs=botCorrect?bot.streak+1:0;const bp=calculateScore({correct:botCorrect,responseMs:botElapsed,questionTimeMs:r.settings.questionTime*1000,streak:bs});const br={answerId:id('answer'),playerId:bot.playerId,questionId:q.id,answer:botAnswer,correct:botCorrect,responseTime:botElapsed,points:bp,timestamp:Date.now()};map.set(bot.playerId,br);bot.answers.push(br);bot.score+=bp;bot.streak=bs;bot.maxStreak=Math.max(bot.maxStreak,bs);if(botCorrect)bot.correctAnswers++;else bot.wrongAnswers++}}
return{record:rec,accepted:true}}
async function getQuestionResult({roomCode,playerId}){await delay(120);const r=db.rooms.get(roomCode);get(r,playerId);const q=r.questions[r.questionIndex];const map=r.answersByQuestion.get(q.id)||new Map();const ranking=[...r.players].sort((a,b)=>b.score-a.score).map((p,i)=>({position:i+1,playerId:p.playerId,name:p.name,score:p.score}));const own=map.get(playerId);return{questionId:q.id,correctAnswer:q.correctAnswer,explanation:q.explanation,correctCount:[...map.values()].filter(x=>x.correct).length,answeredCount:map.size,ownResult:own||null,ranking}}
async function nextQuestion({roomCode,hostId}){await delay(220);const r=db.rooms.get(roomCode);if(r.hostId!==hostId)throwError('UNAUTHORIZED','Somente o anfitrião pode avançar.');if(r.status!=='QUESTION')throwError('INVALID_REQUEST','Estado inválido.');if(r.questionIndex>=r.questions.length-1){r.status='FINISHED';r.currentQuestion=null;return publicRoom(r)}r.questionIndex++;r.currentQuestion=r.questions[r.questionIndex].id;r.questionStartedAt=Date.now();r.answersByQuestion.set(r.currentQuestion,new Map());return publicRoom(r)}
async function getLeaderboard({roomCode,playerId}){const r=db.rooms.get(roomCode);get(r,playerId);return [...r.players].sort((a,b)=>b.score-a.score).map((p,i)=>({position:i+1,playerId:p.playerId,name:p.name,score:p.score,correctAnswers:p.correctAnswers,wrongAnswers:p.wrongAnswers,maxStreak:p.maxStreak,accuracy:p.answers.length?Math.round(p.correctAnswers/p.answers.length*100):0,avgResponse:p.answers.length?Math.round(p.answers.reduce((s,a)=>s+a.responseTime,0)/p.answers.length):0,alive:p.alive}))}
async function removePlayer({roomCode,hostId,playerId}){const r=db.rooms.get(roomCode);if(r.hostId!==hostId)throwError('UNAUTHORIZED','Somente o anfitrião pode expulsar.');if(playerId===hostId)throwError('INVALID_REQUEST','O anfitrião não pode ser expulso.');r.players=r.players.filter(p=>p.playerId!==playerId);return publicRoom(r)}
async function addDemoBots({roomCode}){const r=db.rooms.get(roomCode);if(!r)throwError('ROOM_NOT_FOUND','Sala não encontrada.');for(const name of ['Leo','Maria','João','Ana']){if(r.players.some(p=>p.name===name))continue;r.players.push({playerId:id('bot'),name,score:0,answers:[],correctAnswers:0,wrongAnswers:0,streak:0,maxStreak:0,alive:true,joinedAt:Date.now(),isHost:false,isBot:true})}return publicRoom(r)}
export const mockApi={createRoom,joinRoom,addDemoBots,joinRoom,startGame,getQuestion,submitAnswer,getQuestionResult,nextQuestion,getLeaderboard,removePlayer,getPlayers:getRoom,finishGame:async d=>nextQuestion(d)};
